# molecule/default/vars/all.yml
---
test_file: /etc

asdf_binary: /usr/local/bin/asdf

asdf_user: deploy

asdf_plugins:
  - name: ruby
    install:
      - 3.4.3
  - name: nodejs
    install:
      - 23.11.0
      - 22.15.0
    default: 23.11.0
  - name: act
    uninstall:
      - 0.2.77

asdf_ruby_dependencies:
  - libdb-dev
  - libffi-dev
  - libgdbm-dev
  - libgmp-dev
  - libmysqlclient-dev
  - libncurses-dev
  - libpq-dev
  - libreadline-dev
  - libssl-dev
  - libyaml-dev
  - patch
  - rustc
  - uuid-dev
  - zlib1g-dev
