# molecule/default/converge.yml
---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      register: apt_cache_update
      when: ansible_os_family == "Debian"

    - name: Create deploy user
      ansible.builtin.user:
        name: deploy
        createhome: true
        home: /home/deploy
        shell: /bin/bash
        state: present

    - name: Create plugin install directory for act
      ansible.builtin.file:
        path: /home/deploy/.asdf/installs/act/0.2.77/bin
        state: directory
        mode: "0755"
        owner: deploy
        group: deploy
      become: true
      become_user: deploy
      changed_when: false

    - name: Copy act binary to install directory
      ansible.builtin.copy:
        src: files/act
        dest: /home/deploy/.asdf/installs/act/0.2.77/bin/act
        owner: deploy
        group: deploy
        mode: "0755"
      become: true
      become_user: deploy
      changed_when: false

    - name: Set asdf_plugins
      ansible.builtin.set_fact:
        asdf_plugins:
          - name: ruby
            install:
              - 3.4.3
          - name: nodejs
            install:
              - 23.11.0
              - 22.15.0
            default: 23.11.0
          - name: act
            uninstall:
              - 0.2.77

  roles:
    - { role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}" }
