# molecule/default/converge.yml
---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      register: apt_cache_update
      when: ansible_os_family == "Debian"

    - name: Create deploy user
      ansible.builtin.user:
        name: deploy
        createhome: true
        home: /home/deploy
        shell: /bin/bash
        state: present

    - name: Set asdf_plugins
      ansible.builtin.set_fact:
        asdf_plugins:
          - name: ruby
          - name: nodejs

  roles:
    - { role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}" }
